openapi: 3.0.3
info:
  version: "2.4.0"
  title: API de Moneris
  description: |
    Plateforme des API de Moneris
  termsOfService: https://www.moneris.com/fr-ca/juridiques/conditions-utilisation
  contact:
    url: https://api-developer.moneris.com
    email: UnifiedAPI@moneris.com
  license:
    name: Moneris
    url: https://developer.moneris.com/Agreements/Terms%20of%20Use
  x-audience: external-public
servers:
  - url: https://api.moneris.io
    description: Serveur de production (utilise des données réelles)
  - url: https://api.sb.moneris.io
    description: Serveur de test (utilise des données de test)
tags:
  - name: Paiements
    description: Effectuer et gérer les paiements
  - name: Modes de Paiement
    description: Créer et gérer les modes paiements
  - name: Remboursements
    description: Effectuer et gérer les remboursements
  - name: Validations
    description: Effectuer et gérer les validations
  - name: Clients
    description: Créer et gérer les clients
  - name: Authentification 3DS
    description: Effectuer des authentications 3D-Secure sur des moyens de paiements
  - name: Kount
    description: Effectuer et gérer les demandes d'évaluation des risques Kount
  - name: Abonnements
    description: Effectuer et gérer les Abonnements
  - name: Paiements en plusieurs versements
    description: Effectuer et gérer les paiements en plusieurs versements
  - name: Commerçants
    description: Gérer les commerçants
  - name: Commandes de terminaux et de services
    description: Gérer les commandes de terminaux et de services Moneris
  - name: Produits
    description: Recommandations de produits
  - name: Événements
    description: Recevoire des événements en temps réel concernant vos ressources API de Moneris.
paths:
  /payments:
    get:
      summary: Liste des paiements
      description: Renvoie une liste paginée de paiements.
      operationId: getPayments
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Paiements
    post:
      summary: Créer un paiement
      description: Cette opération est utilisée pour initier un paiement.
      operationId: createPayments
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Paiements
  /payments/{payment-id}:
    get:
      summary: Récupérer le paiement
      description: Récupérer un paiement à l’aide de son ID de paiement
      operationId: getPayment
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Paiements
  /payments/{payment-id}/cancel:
    post:
      summary: Annuler le paiement
      description: Annuler un paiement. Cette opération peut ne pas être possible si le paiement a été effectué.
      operationId: cancelPayment
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Paiements
  /payments/{payment-id}/complete:
    post:
      summary: Effectuer le paiement
      description: Cela permettra de saisir efficacement un paiement qui a été autorisé.
      operationId: completePayment
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Paiements
  /payment-methods:
    get:
      summary: Répertorier les modes de paiement
      description: Récupère une liste paginée des modes de paiement.
      operationId: getPaymentMethods
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Modes de Paiement
    post:
      summary: Créer un mode de paiement
      description: Créez un mode de paiement.
      operationId: createPaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Modes de Paiement
  /payment-methods/{payment-method-id}:
    get:
      summary: Récupérer le mode de paiement
      description: Récupérer un moyen de paiement par ID
      operationId: getPaymentMethod
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Modes de Paiement
    put:
      summary: Mettre à jour le mode de paiement
      description: |
        Mettre à jour le mode de paiement référencé par son Id. 
        Certaines informations peuvent ne pas être mises à jour si le mode de paiement a été utilisé dans une transaction.
      operationId: updatePaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Modes de Paiement
    delete:
      summary: Supprimer le mode de paiement
      description: Supprime un mode de paiement.
      operationId: deletePaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Modes de Paiement
  /refunds:
    get:
      summary: Liste des remboursements
      description: Renvoie une liste paginée des opérations de remboursement.
      operationId: getRefunds
      security:
        - OAuth2:
            - refund.read
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Remboursements
    post:
      summary: Créer un remboursement
      description: |
        Cette opération est utilisée pour créer un remboursement. 
        Pour les remboursements de paiement, l’ID de paiement est requis tandis que le mode de paiement n’est pas requis.
        Pour les remboursements indépendants, aucun identifiant de paiement n’est requis, mais le mode de paiement est requis.
      operationId: createRefund
      security:
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Remboursements
  /refunds/{refund-id}:
    get:
      summary: Récupérer le remboursement
      description: Récupérer un remboursement par son Id.
      operationId: getRefundById
      security:
        - OAuth2:
            - refund.read
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Remboursements
  /validations:
    description: |
      Paramétrez un mode de paiement pour les paiements futurs. 
      Similaire à un paiement, mais aucun frais n’est créé.
      Utile lors de l’intégration des clients, mais pas pour les facturer tout de suite.
    get:
      summary: Validations de cartes de liste
      description: Renvoie une liste paginée des validations de cartes qui ont été exécutées.
      operationId: getValidations
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
    post:
      summary: Créer une validation de carte
      description: Lancez une nouvelle demande de validation de carte.
      operationId: createValidation
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
  /validations/{validation-id}:
    get:
      summary: Récupérer la validation de la carte.
      description: Récupérer une validation de carte par id.
      operationId: getValidation
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
  /subscriptions:
    post:
      summary: Créer un abonnement
      description: Cette opération permet de créer un abonnement.
      operationId: createSubscriptions
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
    get:
      summary: Lister les abonnements
      description: Renvoie une liste paginée des abonnements.
      operationId: getSubscriptions
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
  /subscriptions/{subscription-id}:
    get:
      summary: Récupérer un abonnement
      description: Récupérer les détails d'un abonnement par identifiant
      operationId: getSubscription
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
    patch:
      summary: Mettre à jour l'abonnement
      description: Mettre à jour l'abonnement
      operationId: updateSubscription
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
  /subscriptions/{subscription-id}/resume:
    post:
      summary: Reprendre un abonnement
      description: |
        Reprend une facturation d'abonnement.
        Lorsqu'une transaction est en attente, elle n'est pas facturée pour le montant récurrent.
        Cependant, le nombre de récurrences restantes continue d'être décrémenté pendant cette période.
      operationId: resumeSubscription
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
  /subscriptions/{subscription-id}/pause:
    post:
      summary: Suspendre un abonnement
      description: |
        Suspend temporairement la facturation d'abonnement.
        Lorsqu'une transaction est en attente, elle n'est pas facturée pour le montant d'abonnement.
        Toutefois, le nombre de transactions d'abonnement restantes continue de diminuer pendant cette période.
      operationId: pauseSubscription
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
  /subscriptions/{subscription-id}/cancel:
    post:
      summary: Annuler un abonnement
      description: Annuler un abonnement.
      operationId: cancelSubscription
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
  /subscriptions/{subscription-id}/extend:
    post:
      summary: Prolonger un abonnement
      description: |-
        Ajoute le nombre donné de transactions d'abonnement au nombre actuel (restant).
        Cela peut être utilisé si un client décide de prolonger un abonnement.
        Cependant, comme ce nombre doit être positif, il ne peut pas être utilisé pour diminuer le nombre actuel de transactions d'abonnement. Pour cela, utilisez Mettre à jour un abonnement.
      operationId: extendSubscription
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Abonnements
  /customers:
    description: |
      Cette API permet de gérer les clients passés et récurrents.
      Très utile lors du suivi et de la gestion des frais appartenant au même client.
    get:
      summary: Liste des clients
      description: Renvoie une liste paginée de clients.
      operationId: getCustomers
      security:
        - OAuth2:
            - customer.read
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Clients
    post:
      summary: Créer un client
      description: Cette opération permet de créer un nouveau client.
      operationId: createCustomers
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Clients
  /customers/{customer-id}:
    get:
      summary: Récupérer le client
      description: Récupérer un client par son Id.
      operationId: getCustomer
      security:
        - OAuth2:
            - customer.read
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Clients
    put:
      summary: Mettre à jour le client
      description: Met à jour les données du client telles que le nom, l’adresse, etc.
      operationId: updateCustomer
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Clients
    delete:
      summary: Supprimer le client
      description: Supprimer un client par son identifiant
      operationId: deleteCustomer
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Clients
  /three-d-secure/authentications:
    post:
      summary: Créer une authentification
      description: |
        Cette opération permet de créer une demande d’authentification. 
        La demande d’authentification sert à lancer le processus de validation de la carte. 
        Le résultat de cette demande détermine si 3DS est pris en charge par la carte et quel type d’authentification est requis.
      operationId: createAuthentication
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Authentification 3DS
  /three-d-secure/authentications/{authentication-id}:
    get:
      summary: Récupérer l’authentification
      description: Récupérer une authentification par son ID d’authentification
      operationId: getAuthentication
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Authentification 3DS
  /three-d-secure/authentications/{authentication-id}/lookup:
    post:
      summary: Recherche de valeur d’authentification
      description: L’objectif du flux 3-D Secure est de vérifier que le véritable titulaire de la carte fait partie de l’autorisation. Le flux d’authentification est utilisé pour présenter un moyen d’authentifier le titulaire de la carte à l’aide, par exemple, de l’OTP ou d’une méthode d’identification fédérée.
      operationId: authenticationValueLookup
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Authentification 3DS
  /three-d-secure/card-lookups:
    post:
      summary: Recherche de carte 3DS
      operationId: cardLookup
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Authentification 3DS
  /kount-inquiries:
    post:
      summary: Créer une demande Kount
      operationId: createKountInquiry
      security:
        - OAuth2:
            - kount.write
        - ApiKeyAuth: []
      tags:
        - Kount
    get:
      summary: Liste Kount Demandes de renseignements
      operationId: getKountInquiries
      security:
        - OAuth2:
            - kount.read
        - ApiKeyAuth: []
      tags:
        - Kount
  /kount-inquiries/{kount-inquiry-id}:
    get:
      summary: Obtenir Kount Inquiry by Id
      operationId: getKountInquiryById
      security:
        - OAuth2:
            - kount.read
        - ApiKeyAuth: []
      tags:
        - Kount
  /kount-inquiries/{kount-inquiry-id}/assert:
    post:
      summary: Kount Inquiry Assert
      operationId: kountInquiryAssert
      security:
        - OAuth2:
            - kount.write
        - ApiKeyAuth: []
      tags:
        - Kount
  /installments/plans:
    post:
      summary: Recherche de plan d'installments
      description: Retourne la liste des plans d'installments pour lesquels le titulaire de la carte est éligible.
      operationId: installmentLookup
      tags:
        - Installments
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
  /onboarding/merchants:
    post:
      summary: Create Merchant
      description: Submit a merchant payload to create a merchant
      operationId: createMerchant
      security:
        - OAuth2:
            - onboarding.merchant.write
        - ApiKeyAuth: []
      tags:
        - Merchants
  /onboarding/merchants/{merchant-id}:
    get:
      summary: Get the details of a Merchant
      operationId: getMerchantDetailsByMerchantId
      tags:
        - Merchants
      description: |
        Get merchant details by ID
      security:
        - OAuth2:
            - onboarding.merchant.read
        - OAuth2:
            - onboarding.merchant.write
        - ApiKeyAuth: []
    put:
      summary: Submit a merchant payload to update a merchant
      operationId: updateMerchant
      security:
        - OAuth2:
            - onboarding.merchant.write
        - ApiKeyAuth: []
      tags:
        - Merchants
      description: |
        Update merchant based on the supplied payload.
  /onboarding/merchants/{merchant-id}/supplies:
    get:
      summary: List merchant supplies
      operationId: listMerchantSupplies
      security:
        - OAuth2:
            - onboarding.merchant.read
        - OAuth2:
            - onboarding.merchant.write
        - ApiKeyAuth: []
      tags:
        - Merchants
      description: |
        Get merchant supplies by merchant ID
  /onboarding/merchants/{merchant-id}/orders:
    post:
      summary: Create Order
      description: Submit an order payload to create an order for the merchant
      operationId: createOrder
      security:
        - OAuth2:
            - order.write
        - ApiKeyAuth: []
      tags:
        - Orders
    get:
      summary: List orders
      description: Query multiple order status by giving the order ID within a single request
      operationId: getOrdersByOrderIds
      security:
        - OAuth2:
            - onboarding.order.read
        - OAuth2:
            - onboarding.order.write
        - ApiKeyAuth: []
      tags:
        - Orders
  /onboarding/merchants/{merchant-id}/orders/{merchant-order-id}:
    get:
      summary: Retrieve order by Id
      operationId: getOrderDetailsByOrderId
      security:
        - OAuth2:
            - onboarding.order.read
        - OAuth2:
            - onboarding.order.write
        - ApiKeyAuth: []
      tags:
        - Orders
      description: |
        Get order details by ID
    put:
      summary: Update an order by ID
      operationId: updateOrder
      security:
        - OAuth2:
            - order.write
        - ApiKeyAuth: []
      tags:
        - Orders
  /onboarding/product-recommendations:
    post:
      summary: List Recommended Products
      operationId: getRecommenderProducts
      tags:
        - Products
      description: |
        Get recommender products to fetch multiple items related to a client
      security:
        - OAuth2:
            - onboarding.order.read
        - OAuth2:
            - onboarding.order.write
        - ApiKeyAuth: []
x-webhooks:
  eventNotification:
    post:
      summary: Notification des évenements API de Moneris
      security: []
      operationId: onMonerisEvent
      tags:
        - Événements
      description: Notification des évenements API de Moneris
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
      description: |
        Une clé API est un jeton fourni par un client lors de ses appels API.

        Les clés API sont censées être un secret que seuls le client et le serveur connaissent.
    OAuth2:
      type: oauth2
      description: |
        OAuth 2.0 est un protocole d'autorisation qui donne à un client API un accès limité aux données utilisateur sur un serveur Web.

        OAuth s'appuie sur des scénarios d'authentification qui permettent au propriétaire de la ressource (utilisateur) de partager le contenu protégé du serveur hébergeant la ressource, sans partager ses informations d'identification. À cette fin, un serveur OAuth 2.0 émet des jetons d'accès que les applications clientes peuvent utiliser pour accéder aux ressources protégées au nom du propriétaire de la ressource.

        Moneris recommande l'utilisation d'OAuth 2.0 car il fournit des niveaux d'autorisation précis.
      flows:
        clientCredentials:
          tokenUrl: https://api.moneris.io/oauth2/token
          scopes:
            payment.read: accorde un accès en lecture aux API liées au paiement
            payment.write: accorde un accès en lecture et en écriture aux API liées au paiement
            refund.read: accorde un accès en lecture aux remboursements
            refund.write: accorde un accès en lecture et en écriture aux remboursements
            customer.read: accorde un accès en lecture aux données client
            customer.write: accorde un accès en lecture et en écriture aux données client
            kount.read: accorde un accès en lecture aux demandes Kount
            kount.write: accorde un accès en lecture et en écriture aux demandes Kount
            onboarding.merchant.read: Accorde un accès en lecture aux API liées à l'intégration des commerçants
            onboarding.merchant.write: Accorde un accès en lecture et en écriture aux API liées à l'intégration des commerçants
            onboarding.order.read: Accorde un accès en lecture aux API liées aux commandes d'intégration
            onboarding.order.write: Accorde un accès en lecture et en écriture aux API liées aux commandes d'intégration
            field-services.request.read: Accorde un accès en lecture aux API liées aux services sur site
            field-services.request.write: Accorde un accès en lecture et en écriture aux API liées aux services sur site